### PR TITLE
Tracker3 update. JB#53910 OMP#JOLLA-60 

### PR DESCRIPTION
**Pull request by pvuorela**
Recreated https://git.sailfishos.org/mer-core/tracker-miners/merge_requests/8

cc @okodron

### CODE REVIEW

**Comment by adenexter** [comment]
I've built and installed, tracker, tracker-miners, qtdocgallery, libqtsparql and grilo-plugins. Clean builds, I nearly failed to apply the patches for tracker-miners but caught before installing and did a new clean build. And again I'm experiencing database errors from tracker-miners.

Jun 24 15:59:53 JollaC tracker-miner-f[9064]: Could not create store/endpoint: no such table: nrl:Ontology
Jun 24 15:59:58 JollaC tracker-miner-f[9074]: Corrupt database: failed to create resource check statement: no such table: Resource
Jun 24 15:59:58 JollaC tracker-miner-f[9074]: Could not create store/endpoint: Corrupt db file

After which the process exits, restarts, and the cycle repeats. Gallery eventually starts after an attempt to connect to tracker times out.

**Comment by adenexter** [comment]
Update .gitmodules to use the https://github.com/sailfishos-mirror/ mirror.

**Comment by adenexter** [comment]
My database errors went away after deleting /home/defaultuser/.cache/tracker3/files/meta.db and restarting the tracker-miner-fs-3.

Prior to deletion meta.db was an 8192b file which sqlite3 opened without error but also appeared to be completely empty. .schema printed nothing. With debug enabled I get a lot of messages saying the page size has been set to 8192 which would explain the initial size, but it seems like there was some sort of error after that on the first run which left an empty database which caused errors on subsequent attempts to open.

The bad database may have been a holdover from my previous attempt to install these packages which also ran into errors. I'll try on an uncorrupted device and see if the result is different.

**Comment by adenexter** [comment]
All okay on the second device with a reboot immediately after installing.

**Comment by pvuorela** [comment]
Updated to 3.1.2.

**Review by adenexter — APPROVED** [review]

**Comment by pvuorela** [comment]
Added a patch from Andrew, adjusting signal handler setup a bit, hopefully avoiding database corruption if the service gets stopped right after first time start.

**Review by okodron — APPROVED** [review]

**Review by abranson — APPROVED** [review]

**Pull request merged**
